Repository notaryproject/notation, pull requests merged in 2022-12, with the labels that each got.

#454 doc: update CLI help doc for notation sign and verify in RC.1
  cmd/notation/sign.go
  cmd/notation/verify.go
Labels: documentation, UX

#439 spec: update cli sign spec for tag to digest translation
  specs/commandline/sign.md
Labels: spec

#440 spec: update cli verify spec for UX improvement
  specs/commandline/verify.md
Labels: UX, spec

#449 feat: delete old dev release
  .github/workflows/dev-release.yml
Labels: github_actions

#481 update: refactored notation list command
  cmd/notation/list.go
  cmd/notation/manifest.go
  cmd/notation/sign.go
  cmd/notation/verify.go
Labels: enhancement, refactoring

#484 update: added log to notation login and logout commands
  cmd/notation/login.go
  cmd/notation/logout.go
  cmd/notation/registry.go
  pkg/auth/native_store.go
  pkg/auth/native_store_test.go
  specs/commandline/login.md
  specs/commandline/logout.md
Labels: UX

#478 update: added log to notation key and certificate commands
  cmd/notation/cert/add.go
  cmd/notation/cert/generateTest.go
  cmd/notation/cert/list.go
  cmd/notation/cert/show.go
  cmd/notation/key.go
  specs/commandline/certificate.md
  specs/commandline/key.md
Labels: UX
