Repository notaryproject/notation, pull requests merged in 2022-10, with the labels that each got.

#341 Add notation sign CLI spec
  specs/commandline/sign.md
Labels: cli, spec

#333 feat: add policy command
  cmd/notation/main.go
  cmd/notation/policy.go
  cmd/notation/policy_test.go
  docs/hello-signing.md
  internal/ioutil/print.go
Labels: dev

#384 doc: add examples in CLI help doc for notation sign and verify
  cmd/notation/common.go
  cmd/notation/sign.go
  cmd/notation/verify.go
Labels: documentation, UX

#402 clean up on dev-rc.1 branch
  cmd/notation/cache.go
  cmd/notation/cache_test.go
  cmd/notation/cert.go
  cmd/notation/cert_gen.go
  cmd/notation/common.go
  cmd/notation/main.go
  cmd/notation/pull.go
  cmd/notation/pull_test.go
  cmd/notation/push.go
  cmd/notation/push_test.go
  cmd/notation/sign.go
  cmd/notation/sign_test.go
  docs/hello-signing.md
  go.mod
  go.sum
  internal/certificate/cert.go
  internal/cmd/signer.go
  internal/envelope/envelope.go
  internal/envelope/envelope_test.go
  pkg/cache/pull.go
  pkg/cache/signature.go
  specs/notation-cli.md
  test/e2e/internal/utils/checker.go
  test/e2e/internal/utils/exec.go
  test/e2e/internal/utils/init.go
  test/e2e/scenario/sign.go
Labels: dev

#371 spec: add spec for notation verify command
  specs/commandline/verify.md
Labels: cli, spec

#376 spec: add spec for notation version command
  specs/commandline/version.md
Labels: cli, spec

#362 spec: add CLI specs for notation list/login/logout/plugin
  specs/commandline/list.md
  specs/commandline/login.md
  specs/commandline/logout.md
  specs/commandline/plugin.md
Labels: cli, spec

#361 spec: add CLI notation certificate and key specs
  specs/commandline/certificate.md
  specs/commandline/key.md
Labels: cli

#407 updated dependency on dev-rc.1 branch
  cmd/notation/sign.go
  go.mod
  go.sum
Labels: dev

#374 spec: update notation cli md file as index for sub-commands
  specs/notation-cli.md
Labels: cli, spec

#419 feat: implement version command
  .dev.goreleaser.yml
  .goreleaser.yml
  Makefile
  cmd/notation/main.go
  cmd/notation/version.go
  internal/version/version.go
Labels: cli
