Repository notaryproject/notation, pull requests merged in 2023-03, with the labels that each got.

#573 update: changed Sign to use OCI image manifest as default
  cmd/notation/registry.go
  cmd/notation/sign.go
  cmd/notation/sign_test.go
  specs/commandline/sign.md
  test/e2e/run.sh
  test/e2e/suite/command/verify.go
Labels: enhancement, cli

#568 doc: create CLI spec for managing trust policies (phase 1)
  specs/commandline/policy.md
  specs/notation-cli.md
Labels: documentation, spec

#602 feat: use Referrers API per OCI v1.1 spec
  cmd/notation/registry.go
Labels: enhancement

#603 chore: remove Notary v2 reference in CLI repo
  .github/ISSUE_TEMPLATE/bug-or-issue.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  CONTRIBUTING.md
  README.md
  cmd/notation/main.go
  cmd/notation/version.go
  specs/commandline/version.md
  specs/notation-cli.md
Labels: triage
